### ISSUE TITLE
How to split VLCS

### ISSUE THREAD

**Issue by Chen-Ziyang** [koncle/DomainAdaptor#3]
Thank you so much for your open-source contribution, it's a remarkable work! 
I've encountered an issue while downloading and using the VLCS dataset. While I've successfully obtained the raw dataset, I'm unsure how to split it correctly. 
I would appreciate it if you could kindly provide a link to the split dataset or the split files.
I am looking forward to your reply.

**Comment by koncle** [comment]
Thank you for your interest, the split files are all in "dataloader/text_lists". We noticed that our VLCS dataset has a little difference from the web-downloaded dataset and we uploaded the dataset for reproduction in this [link](https://drive.google.com/file/d/1Id-9awHp45iBMeIfJGLkVjjEhouPcNnY/view?usp=drive_link).

**Comment by Chen-Ziyang** [comment]
Thank you for your kindness.
